package SwitchStatemants;
import java.util.Random;
import java.util.Scanner;
public class RAndomTask {
    public static void main(String[] args) {
        Random random = new Random();
        System.out.println("enter your number: ");
        Scanner input = new Scanner(System.in);

        int guessNumber = random.nextInt(10);// this number generated by the programm
        int number_by_user = input.nextInt();

        if ( guessNumber == number_by_user) {
            System.out.println(" You are welcome!");
        } else if ( guessNumber<number_by_user) {
            System.out.println(" too low ");
        } else if (guessNumber>number_by_user) {
            System.out.println("you are too high ");
        }

    }
}
